spring:
  data:
    redis:
      port: '6379'
      host: redis
    mongodb:
      uri: mongodb://localhost:27017/shopping_cart_db
  application:
    name: CartCheckout
logging:
  level:
    com:
      example:
        shoppingcart: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
server:
  port: '8080'
